name: Toni Bauza Mesquida
favicon: null
layout_spectrum: 0.25638
typography_spectrum: 0.51856
title: Baldosa Hidraulica desde Mallorca
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#c8c8c8'
    - '#aaaaaa'
    - '#171717'
    - '#656565'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.4705085242167115
  rhythmicContrast: 0.4468925108667463
purpose: []
